### ISSUE TITLE
Rating shows different in Stopaganda and in Mediabias Factcheck e.g. Business Insider is "High" in Stopaganda and "Mostly factual" in MediaBias Factcheck

### ISSUE THREAD

**Issue by robertinventor** [EG-Freelance/stopaganda-plus#2]
Stopaganda sometimes shows the wrong classification. Is this hard coded rather than dynamically checked?

Example Business Insider shows as mostly factual on Media Bias FactCheck's site while it is shown as high in Stopaganda  in Google Search Results

In Stopaganda in Google:

![image](https://github.com/EG-Freelance/stopaganda-plus/assets/8162860/cfcbb3e6-a3d3-4d59-a61a-e579720f5a89)

In Mediabias Factcheck

![image](https://github.com/EG-Freelance/stopaganda-plus/assets/8162860/e675f6ad-1da1-49db-8548-c55c542f8506)

Thanks for a very useful plugin!

**Comment by EGibbs87** [comment]
Hi Robert,

Thanks for the heads up!

It looks like a dependency had a syntax change at some point, and my automated update script wasn't processing properly.  Typically, the plugins should be updated Sunday with updated sources, so look out for the corrected plugin on Monday or Tuesday).

I'm not going to force up an update now because I want to ensure that the automated script is working properly and won't require manual intervention moving forward.

Thanks again for alerting me!


Erik
