### ISSUE TITLE
feature suggestion: show facutality rating in icon

### ISSUE THREAD

**Issue by GBT7** [EG-Freelance/stopaganda-plus#4]
Hi,

I know one of the main things about this extension is seeing the bias in each news source, but I personally installed it to see the factuality ratings at a quick glance regardless of the bias. I see that the taskbar icon shows the bias rating, so I am making a feature suggestion to be able to change that to show the factuality rating instead, as I personally place more value on factuality and would like to be able to see it without an extra click.

Thanks.

**Comment by mozyhub** [comment]
I installed this addon recently and this was a major peeve of mine!

Instead of showing the blue/red graph branding, it would be great if it used half the icon space to show the bias, and the other half to show the factuality.

**Comment by EGibbs87** [comment]
@mozyhub For what it's worth, my initial desire was to show both, but both Firefox and Chrome (at least as of the time of development, and I don't believe anything has since changed) only allow a single dynamic badge.

@GBT7 I like the idea of putting bias/accuracy in a user setting for the display badge.  Admittedly, I don't really have a lot of free time these days, but when I find some downtime, I'll put some thought into implementing that as a user-defined toggle.

Thanks for the input!

**Comment by EGibbs87** [comment]
I added an entry in the options interface to toggle between BIAS and ACC for the dynamic badge.  Everything seemed to work in testing, so I'm going to keep an eye on it and test it a bit more once the updates are accepted into the plugin stores.

Thanks again!
